#START####

#R code to recreate analyses from: "Assessing the repeatability, robustness to disturbance, and parent-offspring colony resemblance of collective behaviour"
#David N. Fisher, James L.L. Lichtenstein, Raul Costa-Pereira, Justin Yeager, and Jonathan N. Pruitt
#Journal of Evolutionary Biology (MS number: JEB-2019-00458)

#Note that the exact results generated by this code for the multivaraite models run in MCMCglmm will differ from those in the paper
#and indeed each time the analysis is run. This difference is due to the nature of the analysis (i.e. using Monte Carlo Markov Chains) and is not problematic
#in all cases the results should be qualitatively the same and the conclusions equivalent.
#and the phenotypic correlations generated using cor.test should be identical to those in the paper

#any issues please contact David Fisher @ davidnfisher@hotmail.com

setwd("~/McMaster postdoc/Analyses/Eximius")

require(dplyr)
require(MCMCglmm)


#Loading data####

eximius_col_data = read.csv("Eximius_colony_JEB_data.csv", header=T)

summary(eximius_col_data)  

#Correlation between pre- and post-disturbance assays####

#whole dataset, across all treatments

with(eximius_col_data, cor.test(log(wlatency), log(platency)))

#Estimating among-colony correlations

#this code adapted from https://github.com/JonBrommer/Multivariate-Mixed-Models-in-R/wiki/MCMCglmm-examples#organisational-level-3
phen.var2=apply(eximius_col_data[,c("wlatency","platency")],2,function(m) var(log(m),na.rm=T))

prior_bivar<-list(R=list(V=diag(2)*phen.var2*0.7, nu=2),
                    G=list(G1=list(V=diag(2)*0.2*phen.var2, nu=2),
                           G2=list(V=diag(2)*0.1*phen.var2, nu=2)))

#Note you may think we should have 2 date random effects, one for each trait. 
#But its actually not necessary, as each colony is always tested with the same other colonies
#whether its a pre or post test. So although here the post latencies are being associated with the pre dates
#the grouping is still correct i.e. all ARR cols are together on the same day, even if the date is not technically accurate
#this would not be OK if we estimated the among-date covariance, but we do not.

#Model for whole dataset

lat_ppbivar_m = MCMCglmm(cbind(log(wlatency), log(platency)) ~ trait-1 +
                       trait:(scale(trial, scale=FALSE) + scale(log(volume))), 
                       random =~ us(trait):colony +
                       idh(trait):wdate,
                       rcov =~ idh(trait):units,
                       family = c("gaussian","gaussian"),
                       prior = prior_bivar,
                       nitt=550000,
                       burnin=50000,
                       thin=100,
                       verbose = F,
                       pr = F,
                       data = eximius_col_data)
summary(lat_ppbivar_m)
plot(lat_ppbivar_m)
posterior.mode(lat_ppbivar_m$VCV)

#Repeatability of pre-disturbance assays
pre_ac_rpt = lat_ppbivar_m$VCV[,1]/(lat_ppbivar_m$VCV[,1]+lat_ppbivar_m$VCV[,5]+lat_ppbivar_m$VCV[,7])
posterior.mode(pre_ac_rpt)
HPDinterval(pre_ac_rpt)

#Repeatability of post-disturbance assays
post_ac_rpt = lat_ppbivar_m$VCV[,4]/(lat_ppbivar_m$VCV[,4]+lat_ppbivar_m$VCV[,6]+lat_ppbivar_m$VCV[,8])
posterior.mode(post_ac_rpt)
HPDinterval(post_ac_rpt)

#Among-colony correlation between pre- and post-disturbance assays
pp_ac_corr = lat_ppbivar_m$VCV[,2]/(lat_ppbivar_m$VCV[,1]*lat_ppbivar_m$VCV[,4])^.5
posterior.mode(pp_ac_corr)
HPDinterval(pp_ac_corr)


#Now fit model to each treatment separately

#Control

#phenotypic corr 
with(eximius_col_data[eximius_col_data$treatment=="C",], cor.test(log(wlatency), log(platency)))

#Multivariate model
lat_ppbivar_mC = MCMCglmm(cbind(log(wlatency), log(platency)) ~ trait-1 +
                         trait:(scale(trial, scale=FALSE) + scale(log(volume))), 
                         random =~ us(trait):colony+
                         idh(trait):wdate,
                         rcov =~ idh(trait):units,
                         family = c("gaussian","gaussian"),
                         prior = prior_bivar,
                         nitt=550000,
                         burnin=50000,
                         thin=100,
                         verbose = F,
                         pr = F,
                         data = eximius_col_data[eximius_col_data$treatment=="C",])
summary(lat_ppbivar_mC)
plot(lat_ppbivar_mC)
posterior.mode(lat_ppbivar_mC$VCV)


#Among-colony correlation between pre- and post-disturbance trials, with "_C" suffix for "Control".

pp_ac_corr_C = lat_ppbivar_mC$VCV[,2]/(lat_ppbivar_mC$VCV[,1]*lat_ppbivar_mC$VCV[,4])^.5
posterior.mode(pp_ac_corr_C)
HPDinterval(pp_ac_corr_C)


#Procedural control

#phenotypic corr 
with(eximius_col_data[eximius_col_data$treatment=="P",], cor.test(log(wlatency), log(platency)))

#multivariate model
lat_ppbivar_mP = MCMCglmm(cbind(log(wlatency), log(platency)) ~ trait-1 +
                          trait:(scale(trial, scale=FALSE) + scale(log(volume))), 
                          random =~ us(trait):colony +
                          idh(trait):wdate ,
                          rcov =~ idh(trait):units,
                          family = c("gaussian","gaussian"),
                          prior = prior_bivar,
                          nitt=550000,
                          burnin=50000,
                          thin=100,
                          verbose = F,
                          pr = F,
                          data = eximius_col_data[eximius_col_data$treatment=="P",])
summary(lat_ppbivar_mP)
plot(lat_ppbivar_mP)
posterior.mode(lat_ppbivar_mP$VCV)

#Among-colony correlation between pre- and post-disturbance trials, with "_P" suffix for "Procedural control".

pp_ac_corr_P = lat_ppbivar_mP$VCV[,2]/(lat_ppbivar_mP$VCV[,1]*lat_ppbivar_mP$VCV[,4])^.5
posterior.mode(pp_ac_corr_P)
HPDinterval(pp_ac_corr_P)


#Removal

#phenotypic correlation
with(eximius_col_data[eximius_col_data$treatment=="R",], cor.test(log(wlatency), log(platency)))

#Multivariate model
lat_ppbivar_mR = MCMCglmm(cbind(log(wlatency), log(platency)) ~ trait-1 +
                          trait:(scale(trial, scale=FALSE) + scale(log(volume))), 
                          random =~ us(trait):colony +
                          idh(trait):wdate ,
                          rcov =~ idh(trait):units,
                          family = c("gaussian","gaussian"),
                          prior = prior_bivar,
                          nitt=550000,
                          burnin=50000,
                          thin=100,
                          verbose = F,
                          pr = F,
                          data = eximius_col_data[eximius_col_data$treatment=="R",])
summary(lat_ppbivar_mR)
plot(lat_ppbivar_mR)
posterior.mode(lat_ppbivar_mR$VCV)

#Among-colony correlation between pre- and post-disturbance trials, with "_R" suffix for "Removal".

pp_ac_corr_R = lat_ppbivar_mR$VCV[,2]/(lat_ppbivar_mR$VCV[,1]*lat_ppbivar_mR$VCV[,4])^.5
posterior.mode(pp_ac_corr_R)
HPDinterval(pp_ac_corr_R)


#Correlations between pre-disturbance, laboratory and bud colony assays####
# Initial buds####

#phenotypic correlations
with(eximius_col_data, cor.test(log(wlatency), log(llatency)))
with(eximius_col_data, cor.test(log(wlatency), log(blatency)))
with(eximius_col_data, cor.test(log(llatency), log(blatency)))

#Among-colony correlations

phen.var3=apply(eximius_col_data[,c("wlatency","llatency", "blatency")],2,function(m) var(log(m),na.rm=T)) 

prior_trivar<-list(R=list(V=diag(3)*phen.var3*0.7, nu=2),
                    G=list(G1=list(V=diag(3)*0.2*phen.var3, nu=2),
                           G1=list(V=diag(3)*0.1*phen.var3, nu=2)))


lat_trivar_m = MCMCglmm(cbind(log(wlatency), log(llatency), log(blatency)) ~ trait-1 +
                          trait:scale(trial, scale=FALSE) +
                           at.level(trait,1):scale(log(volume)) +
                           at.level(trait,2):scale(adults) +
                           at.level(trait,3):scale(adults), 
                         random =~ us(trait):colony +
                                  idh(trait):wdate,
                         rcov =~ idh(trait):units,
                         family = c("gaussian","gaussian","gaussian"),
                         prior = prior_trivar,
                         nitt=550000,
                         burnin=50000,
                         thin=100,
                         verbose = F,
                         pr = F,
                         data = eximius_col_data)
summary(lat_trivar_m)
plot(lat_trivar_m)
posterior.mode(lat_trivar_m$VCV)

#Among-colony correlation between pre-disturbance and laboratory assays
pl_ac_corr = lat_trivar_m$VCV[,2]/(lat_trivar_m$VCV[,1]*lat_trivar_m$VCV[,5])^.5
posterior.mode(pl_ac_corr)
HPDinterval(pl_ac_corr)

#Among-colony correlation between pre-disturbance and initial bud assays
pb_ac_corr = lat_trivar_m$VCV[,3]/(lat_trivar_m$VCV[,1]*lat_trivar_m$VCV[,9])^.5
posterior.mode(pb_ac_corr)
HPDinterval(pb_ac_corr)

#Among-colony correlation between laboratory and initial bud assays
lb_ac_corr = lat_trivar_m$VCV[,6]/(lat_trivar_m$VCV[,5]*lat_trivar_m$VCV[,9])^.5
posterior.mode(lb_ac_corr)
HPDinterval(lb_ac_corr)

#Repeatability of laboratory assays
lab_ac_rpt = lat_trivar_m$VCV[,5]/(lat_trivar_m$VCV[,5]+lat_trivar_m$VCV[,11]+lat_trivar_m$VCV[,14])
posterior.mode(lab_ac_rpt )
HPDinterval(lab_ac_rpt )

#Repeatability of initial bud assays
bud_ac_rpt = lat_trivar_m$VCV[,9]/(lat_trivar_m$VCV[,9]+lat_trivar_m$VCV[,12]+lat_trivar_m$VCV[,15])
posterior.mode(bud_ac_rpt)
HPDinterval(bud_ac_rpt)

#for repeatability of pre-disturbance assays see lines 67-69

# Settled buds####
#repeat with bud trials 4-6 instead of 1-3, as this is "settled" behaviour 

#note trials are still labelled 1-3, but that was for matching with pre-disturbance measures, 
#for the bud trials they do still reflect trials 4-6 as described in the paper.

#phenotypic
with(eximius_col_data, cor.test(log(wlatency), log(blatency_s)))
with(eximius_col_data, cor.test(log(llatency), log(blatency_s)))

#Among-colony correlations

lat_trivar_m_b = MCMCglmm(cbind(log(wlatency), log(llatency), log(blatency_s)) ~ trait-1 +
                          trait:scale(trial, scale=FALSE) +
                          at.level(trait,1):scale(log(volume)) +
                          at.level(trait,2):scale(adults) +
                          at.level(trait,3):scale(adults), 
                        random =~ us(trait):colony +
                                 idh(trait):wdate,
                        rcov =~ idh(trait):units,
                        family = c("gaussian","gaussian","gaussian"),
                        prior = prior_trivar,
                        nitt=550000,
                        burnin=50000,
                        thin=100,
                        verbose = F,
                        pr = F,
                        data = eximius_col_data)
summary(lat_trivar_m_b)
plot(lat_trivar_m_b)
posterior.mode(lat_trivar_m_b$VCV) 

#Repeatability of settled bud assays
bud_ac_rpt_b = lat_trivar_m_b$VCV[,9]/(lat_trivar_m_b$VCV[,9]+lat_trivar_m_b$VCV[,12]+lat_trivar_m_b$VCV[,15])
posterior.mode(bud_ac_rpt_b)
HPDinterval(bud_ac_rpt_b)

#Among-colony correlation between pre-disturbance and settled bud assays
pb_ac_corr_b = lat_trivar_m_b$VCV[,3]/(lat_trivar_m_b$VCV[,1]*lat_trivar_m_b$VCV[,9])^.5
posterior.mode(pb_ac_corr_b)
HPDinterval(pb_ac_corr_b)

#Among-colony correlation between laboratory and settled bud assays
lb_ac_corr_b = lat_trivar_m_b$VCV[,6]/(lat_trivar_m_b$VCV[,5]*lat_trivar_m_b$VCV[,9])^.5
posterior.mode(lb_ac_corr_b)
HPDinterval(lb_ac_corr_b)



#Post-hoc test: Does elevation drive the pre-disturbance - settled bud covariance?####
lat_trivar_m_e = MCMCglmm(cbind(log(wlatency), log(llatency), log(blatency_s)) ~ trait-1 +
                            trait:scale(trial, scale=FALSE) +
                            trait:scale(elevation) +
                            at.level(trait,1):scale(log(volume)) +
                            at.level(trait,2):scale(adults) +
                            at.level(trait,3):scale(adults), 
                          random =~ us(trait):colony +
                          idh(trait):wdate,
                          rcov =~ idh(trait):units,
                          family = c("gaussian","gaussian","gaussian"),
                          prior = prior_trivar,
                          nitt=550000,
                          burnin=50000,
                          thin=100,
                          verbose = F,
                          pr = F,
                          data = eximius_col_data)
summary(lat_trivar_m_e)
plot(lat_trivar_m_e)
posterior.mode(lat_trivar_m_e$VCV)

#Among-colony correlation between pre-disturbance and laboratory assays, controlling for elevation
pl_ac_corr_e = lat_trivar_m_e$VCV[,2]/(lat_trivar_m_e$VCV[,1]*lat_trivar_m_e$VCV[,5])^.5
posterior.mode(pl_ac_corr_e)
HPDinterval(pl_ac_corr_e)

#Among-colony correlation between pre-disturbance and settled bud assays, controlling for elevation
pb_ac_corr_e = lat_trivar_m_e$VCV[,3]/(lat_trivar_m_e$VCV[,1]*lat_trivar_m_e$VCV[,9])^.5
posterior.mode(pb_ac_corr_e)
HPDinterval(pb_ac_corr_e)

#Among-colony correlation between laboratory and settled bud assays, controlling for elevation
lb_ac_corr_e = lat_trivar_m_e$VCV[,6]/(lat_trivar_m_e$VCV[,5]*lat_trivar_m_e$VCV[,9])^.5
posterior.mode(lb_ac_corr_e)
HPDinterval(lb_ac_corr_e)

#END####
